/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package msdatabase;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Lenovo
 */
public class Main extends javax.swing.JFrame {
JFrame fr=new JFrame();
JPanel p1=new JPanel();
JPanel p2= new JPanel();
public static  String username;

    public static String getUsername() {
        return username;
    }

    public static void setUsername(String u) {
        username = u;
    }


    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
      fr.setSize(400, 350);
         p1.add(jLabel1);
         p1.add(jTextField1);
         
         p1.add(jLabel2);
         
         p1.add(jPasswordField1);
         
        p1.setLayout(new GridLayout(2,2));
         p2.add(jButton1);
        
        fr.add(p1, new BorderLayout().NORTH);
         fr.add(p2, new BorderLayout().SOUTH);
         fr.setVisible(true);
      
        p1.setBackground(Color.ORANGE);
        p2.setBackground(Color.ORANGE);
        fr.getContentPane().setBackground(Color.ORANGE);
        
       fr.setLocationRelativeTo(null);
       //setUsername(jTextField1.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
 
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 255));

        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("LOGIN");

        jLabel2.setText("PASSWORD");

        jPasswordField1.setText("jPasswordField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPasswordField1)
                            .addComponent(jTextField1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jButton1)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(jButton1)
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
       
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
    try {
        DatabaseLogin l=new DatabaseLogin();
        HashMap<Integer,User> map = new HashMap<>();
       
        map= l.read();
   
        String login;
        String heslo;
        login=jTextField1.getText();
        heslo=jPasswordField1.getText();
          /// System.out.print(map.get(1));
        ///System.out.print(login);
        
      if((map.get(1).login.equals(login)) && (map.get(1).heslo.equals(heslo))           )
            {
        
        GUI m= new GUI();
        m.createAndShowGUI();
        setUsername("manager");
   
        
            map= l.read();
                for (int u=1;u<map.size();u++)    if (map.get(u).id==1) setUsername("manager");
 
     
     
     
        fr.setVisible(false);
        }
        
         if((map.get(2).login.equals(login)) && (map.get(2).heslo.equals(heslo))           )
            {
        
        GUI m= new GUI();
        m.createAndShowGUI();
        setUsername("admin");
       // Stred2.setUsername("admin");
          // Stred2.username="admin";
            map= l.read();
          
     for (int u=1;u<map.size();u++)    if (map.get(u).id==2){ 
         
      setUsername("admin");  
    /// Stred2.username="admin";
     
  //   Stred2.setUsername("admin");
     
     }
        fr.setVisible(false);
        }
         
          
            
            
                
                
             
         else {   setUsername("host");
                  map= l.read();
            /// System.out.println(  "heslo mapa"+map.get(4).heslo);
             
                   ///  System.out.println( "heslo mapa"+ map.get(4).login );
             login=jTextField1.getText(); 
               heslo=jPasswordField1.getText();
             
            // System.out.println( login);System.out.println( heslo);
                       
                for (int u=2;u<=map.size();u++)  
           
              if((map.get(u).login.equals(login)) && (map.get(u).heslo.equals(heslo))           )
                      
                 {      
          
          
             
         GUI m= new GUI();
        m.createAndShowGUI();
     
   
     
        fr.setVisible(false);
         
         
         
         }}    
         
         
         
         
        
    } catch (SQLException ex) {
        Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
    }
  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
          
                
             Main m=new Main();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
